### ISSUE TITLE
Link to Playground Demo website is broken 

### ISSUE THREAD

**Issue by merfymerf** [oasisprotocol/playground#19]
https://playground.oasis.io/ returns 404

**Comment by matevz** [comment]
Where did you find this link? The correct link is https://playground.oasis.io/demo-voting

**Comment by matevz** [comment]
Ah, you're referring to the index page of all the playground demos. That doesn't exist yet.

**Comment by matevz** [comment]
Implemented in ae572bc39cc876132eb7ff5e63c4bd1b0ba57bcd as static html. A web app for browsing through the examples will be deployed after #22 is in.
