### ISSUE TITLE
Hide Demo section in the Project dialog, if no demo link provided

### ISSUE THREAD

**Issue by matevz** [oasisprotocol/playground#35]
Some projects do not have a deployed demo available (e.g. starter-project, sapphire-paratime examples). In this case, "Demo:" section on the right should not be rendered.

**Comment by kaja-osojnik** [comment]
Fixed in the following commit: https://github.com/oasisprotocol/playground/pull/33/commits/82985fd712ed7ba95cf9521be5436672e93f76cc
