### ISSUE TITLE
Add per-dApp URL

### ISSUE THREAD

**Issue by matevz** [oasisprotocol/playground#40]
Currently, you can't view details of multiple dApps at once, for example in multiple tabs, because the dApp name or image doesn't point to a link where you would be able to use "Open in new window". Add links (#dapp-name anchors?) so that you could open a dApp in new window. This would also be useful for referencing a specific dApp from outside.

cc @peternose

**Comment by kaja-osojnik** [comment]
Implemented in: [https://github.com/oasisprotocol/playground/pull/50](https://github.com/oasisprotocol/playground/pull/50)

**Comment by lukaw3d** [comment]
I think this is not worth maintaining

**Comment by lukaw3d** [comment]
Do we want to include the large complexity of react-router-dom for this small inconvenience? Do we want to reimplement and maintain small complexity of routing by ourselves? (https://github.com/oasisprotocol/playground/pull/50/commits/7926267c64a13816def2d0d28b30f28b6a804e76 mixes both)

**Comment by lukaw3d** [comment]
bump

**Comment by lukaw3d** [comment]
Fixed in https://github.com/oasisprotocol/playground/pull/50

Did add react-router, but without routes. Only:
- `<Link>`
- reactive `location.hash` from useLocation()

Remaining question: https://github.com/oasisprotocol/playground/pull/50#discussion_r1621047912
