### ISSUE TITLE
Add a Contribute button

### ISSUE THREAD

**Issue by matevz** [oasisprotocol/playground#41]
To encouraged people to add their own dApps, I would beside the link in the text also add a button next to a text e.g. a transparent button similar to Filters button above the Filter button saying "Contribute" or "Add your dApp".

cc @peternose

**Comment by kaja-osojnik** [comment]
Imlemented in PR: https://github.com/oasisprotocol/playground/pull/48[https://github.com/oasisprotocol/playground/pull/48](url)
