### ISSUE TITLE
Add ParaTime field

### ISSUE THREAD

**Issue by matevz** [oasisprotocol/playground#42]
The ParaTime field is missing in the UI.

1. On the landing page I suggest we write the ParaTime name (or Consensus) below the programming language and reduce the bottom margin.
   | Before | After |
   |-----------|----------|
   | ![image](https://github.com/oasisprotocol/playground/assets/83672/4022bf03-2268-4660-86cc-f2e356858e8e) | ![image](https://github.com/oasisprotocol/playground/assets/83672/a93a65ca-8a88-4ac2-95bb-36f4d56958dc) |
2. In the dApp details page I suggest we reorganize the left part and use grid layout:
   ```
   A short demo which connects to the Oasis
   Authenticator and obtains the user ID stored
   on Sapphire, if the authentication is
   successful.
   
   Last updated:                       Created:
   2024-01-01                        2023-10-01
   
   Languages:                        ParaTimes:
   TypeScript                          Sapphire

   Tags:
   Gasless, AuthZN, React


cc @peternose

**Comment by kaja-osojnik** [comment]
Implemented in [https://github.com/oasisprotocol/playground/pull/46](https://github.com/oasisprotocol/playground/pull/46 )
